(function(){var h={},mt={},c={id:"b88cfc1ccab788f0903cac38c894caa3",dm:["jb51.net"],js:"tongji.baidu.com/hm-web/js/",etrk:[],icon:'',ctrk:false,align:-1,nv:-1,vdur:1800000,age:31536000000,rec:1,rp:[[11473, 2]],trust:0,vcard:0,qiao:0,lxb:0,conv:0,comm:0,apps:''};var p=!0,q=null,r=!1;mt.i={};mt.i.Ha=/msie (\d+\.\d+)/i.test(navigator.userAgent);mt.i.cookieEnabled=navigator.cookieEnabled;mt.i.javaEnabled=navigator.javaEnabled();mt.i.language=navigator.language||navigator.browserLanguage||navigator.systemLanguage||navigator.userLanguage||"";mt.i.qa=(window.screen.width||0)+"x"+(window.screen.height||0);mt.i.colorDepth=window.screen.colorDepth||0;mt.cookie={};
mt.cookie.set=function(a,b,d){var f;d.C&&(f=new Date,f.setTime(f.getTime()+d.C));document.cookie=a+"="+b+(d.domain?"; domain="+d.domain:"")+(d.path?"; path="+d.path:"")+(f?"; expires="+f.toGMTString():"")+(d.La?"; secure":"")};mt.cookie.get=function(a){return(a=RegExp("(^| )"+a+"=([^;]*)(;|$)").exec(document.cookie))?a[2]:q};mt.o={};mt.o.ca=function(a){return document.getElementById(a)};mt.o.Da=function(a,b){for(b=b.toUpperCase();(a=a.parentNode)&&1==a.nodeType;)if(a.tagName==b)return a;return q};
(mt.o.R=function(){function a(){if(!a.t){a.t=p;for(var b=0,d=f.length;b<d;b++)f[b]()}}function b(){try{document.documentElement.doScroll("left")}catch(f){setTimeout(b,1);return}a()}var d=r,f=[],g;document.addEventListener?g=function(){document.removeEventListener("DOMContentLoaded",g,r);a()}:document.attachEvent&&(g=function(){"complete"===document.readyState&&(document.detachEvent("onreadystatechange",g),a())});(function(){if(!d)if(d=p,"complete"===document.readyState)a.t=p;else if(document.addEventListener)document.addEventListener("DOMContentLoaded",
g,r),window.addEventListener("load",a,r);else if(document.attachEvent){document.attachEvent("onreadystatechange",g);window.attachEvent("onload",a);var f=r;try{f=window.frameElement==q}catch(n){}document.documentElement.doScroll&&f&&b()}})();return function(b){a.t?b():f.push(b)}}()).t=r;mt.event={};mt.event.e=function(a,b,d){a.attachEvent?a.attachEvent("on"+b,function(b){d.call(a,b)}):a.addEventListener&&a.addEventListener(b,d,r)};
mt.event.preventDefault=function(a){a.preventDefault?a.preventDefault():a.returnValue=r};mt.m={};mt.m.parse=function(){return(new Function('return (" + source + ")'))()};
mt.m.stringify=function(){function a(a){/["\\\x00-\x1f]/.test(a)&&(a=a.replace(/["\\\x00-\x1f]/g,function(a){var b=d[a];if(b)return b;b=a.charCodeAt();return"\\u00"+Math.floor(b/16).toString(16)+(b%16).toString(16)}));return'"'+a+'"'}function b(a){return 10>a?"0"+a:a}var d={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"};return function(d){switch(typeof d){case "undefined":return"undefined";case "number":return isFinite(d)?String(d):"null";case "string":return a(d);case "boolean":return String(d);
default:if(d===q)return"null";if(d instanceof Array){var g=["["],m=d.length,n,e,l;for(e=0;e<m;e++)switch(l=d[e],typeof l){case "undefined":case "function":case "unknown":break;default:n&&g.push(","),g.push(mt.m.stringify(l)),n=1}g.push("]");return g.join("")}if(d instanceof Date)return'"'+d.getFullYear()+"-"+b(d.getMonth()+1)+"-"+b(d.getDate())+"T"+b(d.getHours())+":"+b(d.getMinutes())+":"+b(d.getSeconds())+'"';n=["{"];e=mt.m.stringify;for(m in d)if(Object.prototype.hasOwnProperty.call(d,m))switch(l=
d[m],typeof l){case "undefined":case "unknown":case "function":break;default:g&&n.push(","),g=1,n.push(e(m)+":"+e(l))}n.push("}");return n.join("")}}}();mt.lang={};mt.lang.d=function(a,b){return"[object "+b+"]"==={}.toString.call(a)};mt.lang.Ia=function(a){return mt.lang.d(a,"Number")&&isFinite(a)};mt.lang.Ka=function(a){return mt.lang.d(a,"String")};mt.localStorage={};
mt.localStorage.A=function(){if(!mt.localStorage.f)try{mt.localStorage.f=document.createElement("input"),mt.localStorage.f.type="hidden",mt.localStorage.f.style.display="none",mt.localStorage.f.addBehavior("#default#userData"),document.getElementsByTagName("head")[0].appendChild(mt.localStorage.f)}catch(a){return r}return p};
mt.localStorage.set=function(a,b,d){var f=new Date;f.setTime(f.getTime()+d||31536E6);try{window.localStorage?(b=f.getTime()+"|"+b,window.localStorage.setItem(a,b)):mt.localStorage.A()&&(mt.localStorage.f.expires=f.toUTCString(),mt.localStorage.f.load(document.location.hostname),mt.localStorage.f.setAttribute(a,b),mt.localStorage.f.save(document.location.hostname))}catch(g){}};
mt.localStorage.get=function(a){if(window.localStorage){if(a=window.localStorage.getItem(a)){var b=a.indexOf("|"),d=a.substring(0,b)-0;if(d&&d>(new Date).getTime())return a.substring(b+1)}}else if(mt.localStorage.A())try{return mt.localStorage.f.load(document.location.hostname),mt.localStorage.f.getAttribute(a)}catch(f){}return q};
mt.localStorage.remove=function(a){if(window.localStorage)window.localStorage.removeItem(a);else if(mt.localStorage.A())try{mt.localStorage.f.load(document.location.hostname),mt.localStorage.f.removeAttribute(a),mt.localStorage.f.save(document.location.hostname)}catch(b){}};mt.sessionStorage={};mt.sessionStorage.set=function(a,b){if(window.sessionStorage)try{window.sessionStorage.setItem(a,b)}catch(d){}};
mt.sessionStorage.get=function(a){return window.sessionStorage?window.sessionStorage.getItem(a):q};mt.sessionStorage.remove=function(a){window.sessionStorage&&window.sessionStorage.removeItem(a)};mt.S={};mt.S.log=function(a,b){var d=new Image,f="mini_tangram_log_"+Math.floor(2147483648*Math.random()).toString(36);window[f]=d;d.onload=d.onerror=d.onabort=function(){d.onload=d.onerror=d.onabort=q;d=window[f]=q;b&&b(a)};d.src=a};mt.J={};
mt.J.ha=function(){var a="";if(navigator.plugins&&navigator.mimeTypes.length){var b=navigator.plugins["Shockwave Flash"];b&&b.description&&(a=b.description.replace(/^.*\s+(\S+)\s+\S+$/,"$1"))}else if(window.ActiveXObject)try{if(b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash"))(a=b.GetVariable("$version"))&&(a=a.replace(/^.*\s+(\d+),(\d+).*$/,"$1.$2"))}catch(d){}return a};
mt.J.Ba=function(a,b,d,f,g){return'<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" id="'+a+'" width="'+d+'" height="'+f+'"><param name="movie" value="'+b+'" /><param name="flashvars" value="'+(g||"")+'" /><param name="allowscriptaccess" value="always" /><embed type="application/x-shockwave-flash" name="'+a+'" width="'+d+'" height="'+f+'" src="'+b+'" flashvars="'+(g||"")+'" allowscriptaccess="always" /></object>'};mt.url={};
mt.url.h=function(a,b){var d=a.match(RegExp("(^|&|\\?|#)("+b+")=([^&#]*)(&|$|#)",""));return d?d[3]:q};mt.url.Fa=function(a){return(a=a.match(/^(https?:)\/\//))?a[1]:q};mt.url.ea=function(a){return(a=a.match(/^(https?:\/\/)?([^\/\?#]*)/))?a[2].replace(/.*@/,""):q};mt.url.M=function(a){return(a=mt.url.ea(a))?a.replace(/:\d+$/,""):a};mt.url.Ea=function(a){return(a=a.match(/^(https?:\/\/)?[^\/]*(.*)/))?a[2].replace(/[\?#].*/,"").replace(/^$/,"/"):q};
h.l={Ga:"http://tongji.baidu.com/hm-web/welcome/ico",Q:"hm.baidu.com/hm.gif",V:"baidu.com",la:"hmmd",ma:"hmpl",ka:"hmkw",ia:"hmci",na:"hmsr",n:0,j:Math.round(+new Date/1E3),protocol:"https:"==document.location.protocol?"https:":"http:",Ja:0,ya:6E5,za:10,Aa:1024,xa:1,w:2147483647,T:"bs cc cf ci ck cl cm cp cw ds ep et fl ja ln lo lt nv rnd si st su v cv lv api tt u".split(" ")};
(function(){var a={k:{},e:function(a,d){this.k[a]=this.k[a]||[];this.k[a].push(d)},r:function(a,d){this.k[a]=this.k[a]||[];for(var f=this.k[a].length,g=0;g<f;g++)this.k[a][g](d)}};return h.p=a})();
(function(){function a(a,f){var g=document.createElement("script");g.charset="utf-8";b.d(f,"Function")&&(g.readyState?g.onreadystatechange=function(){if("loaded"===g.readyState||"complete"===g.readyState)g.onreadystatechange=q,f()}:g.onload=function(){f()});g.src=a;var m=document.getElementsByTagName("script")[0];m.parentNode.insertBefore(g,m)}var b=mt.lang;return h.load=a})();
(function(){function a(){var a="";h.b.a.nv?(a=encodeURIComponent(document.referrer),window.sessionStorage?d.set("Hm_from_"+c.id,a):b.set("Hm_from_"+c.id,a,864E5)):a=(window.sessionStorage?d.get("Hm_from_"+c.id):b.get("Hm_from_"+c.id))||"";return a}var b=mt.localStorage,d=mt.sessionStorage;return h.K=a})();
(function(){var a=mt.o,b=h.l,d=h.load,f=h.K;h.p.e("pv-b",function(){c.rec&&a.R(function(){for(var g=0,m=c.rp.length;g<m;g++){var n=c.rp[g][0],e=c.rp[g][1],l=a.ca("hm_t_"+n);if(e&&!(2==e&&!l||l&&""!==l.innerHTML))l="",l=Math.round(Math.random()*b.w),l=4==e?"http://crs.baidu.com/hl.js?"+["siteId="+c.id,"planId="+n,"rnd="+l].join("&"):"http://crs.baidu.com/t.js?"+["siteId="+c.id,"planId="+n,"from="+f(),"referer="+encodeURIComponent(document.referrer),"title="+encodeURIComponent(document.title),"rnd="+
l].join("&"),d(l)}})})})();(function(){var a=h.l,b=h.load,d=h.K;h.p.e("pv-b",function(){if(c.trust&&c.vcard){var f=a.protocol+"//trust.baidu.com/vcard/v.js?"+["siteid="+c.vcard,"url="+encodeURIComponent(document.location.href),"source="+d(),"rnd="+Math.round(Math.random()*a.w)].join("&");b(f)}})})();
(function(){var a=function(){var a=navigator.userAgent.toLowerCase();if(0<=a.indexOf("chrome")){var d;d=(a=a.match(/chrome\/(\d+)/))?a[1]:-1;var f=window.document,a="track"in f.createElement("track"),f="scoped"in f.createElement("style"),g="v8Locale"in window,m=document.createElement("canvas"),n="seamless"in document.createElement("iframe"),e=r;try{m.getContext("webgl")&&(e=p)}catch(l){}if(!e&&"31"===d)return 1;if(!(d=(n||!e)&&"38"===d))if(d=a)if(d=!f)if(d=!g){var k;a:{d=window.navigator.mimeTypes;
for(k in d)if("application/vnd.chromium.remoting-viewer"===d[k].type){k=p;break a}k=r}d=!k}if(d)return 7;if(a&&f&&g)return 1}return-1}();return h.X=a})();
(function(){function a(){return function(){h.b.a.nv=0;h.b.a.st=4;h.b.a.et=3;h.b.a.ep=h.B.fa()+","+h.B.da();h.b.g()}}function b(){clearTimeout(x);var a;w&&(a="visible"==document[w]);y&&(a=!document[y]);e="undefined"==typeof a?p:a;if((!n||!l)&&e&&k)v=p,s=+new Date;else if(n&&l&&(!e||!k))v=r,t+=+new Date-s;n=e;l=k;x=setTimeout(b,100)}function d(a){var l=document,t="";if(a in l)t=a;else for(var d=["webkit","ms","moz","o"],b=0;b<d.length;b++){var k=d[b]+a.charAt(0).toUpperCase()+a.slice(1);if(k in l){t=
k;break}}return t}function f(a){if(!("focus"==a.type||"blur"==a.type)||!(a.target&&a.target!=window))k="focus"==a.type||"focusin"==a.type?p:r,b()}var g=mt.event,m=h.p,n=p,e=p,l=p,k=p,u=+new Date,s=u,t=0,v=p,w=d("visibilityState"),y=d("hidden"),x;b();(function(){var a=w.replace(/[vV]isibilityState/,"visibilitychange");g.e(document,a,b);g.e(window,"pageshow",b);g.e(window,"pagehide",b);"object"==typeof document.onfocusin?(g.e(document,"focusin",f),g.e(document,"focusout",f)):(g.e(window,"focus",f),
g.e(window,"blur",f))})();h.B={fa:function(){return+new Date-u},da:function(){return v?+new Date-s+t:t}};m.e("pv-b",function(){g.e(window,"unload",a())});return h.B})();
(function(){var a=mt.lang,b=h.l,d=h.load,f={oa:function(f){if((void 0===window._dxt||a.d(window._dxt,"Array"))&&"undefined"!==typeof h.b){var m=h.b.D();d([b.protocol,"//datax.baidu.com/x.js?si=",c.id,"&dm=",encodeURIComponent(m)].join(""),f)}},wa:function(d){if(a.d(d,"String")||a.d(d,"Number"))window._dxt=window._dxt||[],window._dxt.push(["_setUserId",d])}};return h.Z=f})();
(function(){function a(l){for(var b in l)if({}.hasOwnProperty.call(l,b)){var e=l[b];d.d(e,"Object")||d.d(e,"Array")?a(e):l[b]=String(e)}}function b(a){return a.replace?a.replace(/'/g,"'0").replace(/\*/g,"'1").replace(/!/g,"'2"):a}var d=mt.lang,f=mt.m,g=h.l,m=h.p,n=h.Z,e={N:q,q:[],z:0,O:r,init:function(){e.c=0;e.N={push:function(){e.H.apply(e,arguments)}};m.e("pv-b",function(){e.$();e.aa()});m.e("pv-d",e.ba);m.e("stag-b",function(){h.b.a.api=e.c||e.z?e.c+"_"+e.z:""});m.e("stag-d",function(){h.b.a.api=
0;e.c=0;e.z=0})},$:function(){var a=window._hmt;if(a&&a.length)for(var d=0;d<a.length;d++){var b=a[d];switch(b[0]){case "_setAccount":1<b.length&&/^[0-9a-z]{32}$/.test(b[1])&&(e.c|=1,window._bdhm_account=b[1]);break;case "_setAutoPageview":if(1<b.length&&(b=b[1],r===b||p===b))e.c|=2,window._bdhm_autoPageview=b}}},aa:function(){if("undefined"===typeof window._bdhm_account||window._bdhm_account===c.id){window._bdhm_account=c.id;var a=window._hmt;if(a&&a.length)for(var b=0,f=a.length;b<f;b++)d.d(a[b],
"Array")&&"_trackEvent"!==a[b][0]&&"_trackRTEvent"!==a[b][0]?e.H(a[b]):e.q.push(a[b]);window._hmt=e.N}},ba:function(){if(0<e.q.length)for(var a=0,b=e.q.length;a<b;a++)e.H(e.q[a]);e.q=q},H:function(a){if(d.d(a,"Array")){var b=a[0];if(e.hasOwnProperty(b)&&d.d(e[b],"Function"))e[b](a)}},_trackPageview:function(a){if(1<a.length&&a[1].charAt&&"/"==a[1].charAt(0)){e.c|=4;h.b.a.et=0;h.b.a.ep="";h.b.F?(h.b.a.nv=0,h.b.a.st=4):h.b.F=p;var b=h.b.a.u,d=h.b.a.su;h.b.a.u=g.protocol+"//"+document.location.host+
a[1];e.O||(h.b.a.su=document.location.href);h.b.g();h.b.a.u=b;h.b.a.su=d}},_trackEvent:function(a){2<a.length&&(e.c|=8,h.b.a.nv=0,h.b.a.st=4,h.b.a.et=4,h.b.a.ep=b(a[1])+"*"+b(a[2])+(a[3]?"*"+b(a[3]):"")+(a[4]?"*"+b(a[4]):""),h.b.g())},_setCustomVar:function(a){if(!(4>a.length)){var d=a[1],f=a[4]||3;if(0<d&&6>d&&0<f&&4>f){e.z++;for(var s=(h.b.a.cv||"*").split("!"),t=s.length;t<d-1;t++)s.push("*");s[d-1]=f+"*"+b(a[2])+"*"+b(a[3]);h.b.a.cv=s.join("!");a=h.b.a.cv.replace(/[^1](\*[^!]*){2}/g,"*").replace(/((^|!)\*)+$/g,
"");""!==a?h.b.setData("Hm_cv_"+c.id,encodeURIComponent(a),c.age):h.b.pa("Hm_cv_"+c.id)}}},_setReferrerOverride:function(a){1<a.length&&(h.b.a.su=a[1].charAt&&"/"==a[1].charAt(0)?g.protocol+"//"+window.location.host+a[1]:a[1],e.O=p)},_trackOrder:function(b){b=b[1];d.d(b,"Object")&&(a(b),e.c|=16,h.b.a.nv=0,h.b.a.st=4,h.b.a.et=94,h.b.a.ep=f.stringify(b),h.b.g())},_trackMobConv:function(a){if(a={webim:1,tel:2,map:3,sms:4,callback:5,share:6}[a[1]])e.c|=32,h.b.a.et=93,h.b.a.ep=a,h.b.g()},_trackRTPageview:function(b){b=
b[1];d.d(b,"Object")&&(a(b),b=f.stringify(b),512>=encodeURIComponent(b).length&&(e.c|=64,h.b.a.rt=b))},_trackRTEvent:function(b){b=b[1];if(d.d(b,"Object")){a(b);b=encodeURIComponent(f.stringify(b));var k=function(a){var b=h.b.a.rt;e.c|=128;h.b.a.et=90;h.b.a.rt=a;h.b.g();h.b.a.rt=b},u=b.length;if(900>=u)k.call(this,b);else for(var u=Math.ceil(u/900),s="block|"+Math.round(Math.random()*g.w).toString(16)+"|"+u+"|",t=[],v=0;v<u;v++)t.push(v),t.push(b.substring(900*v,900*v+900)),k.call(this,s+t.join("|")),
t=[]}},_setUserId:function(a){a=a[1];n.oa();n.wa(a)}};e.init();h.W=e;return h.W})();
(function(){function a(){"undefined"==typeof window["_bdhm_loaded_"+c.id]&&(window["_bdhm_loaded_"+c.id]=p,this.a={},this.F=r,this.init())}var b=mt.url,d=mt.S,f=mt.J,g=mt.lang,m=mt.cookie,n=mt.i,e=mt.localStorage,l=mt.sessionStorage,k=h.l,u=h.X,s=h.p;a.prototype={G:function(a,b){a="."+a.replace(/:\d+/,"");b="."+b.replace(/:\d+/,"");var d=a.indexOf(b);return-1<d&&d+b.length==a.length},P:function(a,b){a=a.replace(/^https?:\/\//,"");return 0===a.indexOf(b)},s:function(a){for(var d=0;d<c.dm.length;d++)if(-1<
c.dm[d].indexOf("/")){if(this.P(a,c.dm[d]))return p}else{var e=b.M(a);if(e&&this.G(e,c.dm[d]))return p}return r},D:function(){for(var a=document.location.hostname,b=0,d=c.dm.length;b<d;b++)if(this.G(a,c.dm[b]))return c.dm[b].replace(/(:\d+)?[\/\?#].*/,"");return a},L:function(){for(var a=0,b=c.dm.length;a<b;a++){var d=c.dm[a];if(-1<d.indexOf("/")&&this.P(document.location.href,d))return d.replace(/^[^\/]+(\/.*)/,"$1")+"/"}return"/"},ga:function(){if(!document.referrer)return k.j-k.n>c.vdur?1:4;var a=
r;this.s(document.referrer)&&this.s(document.location.href)?a=p:(a=b.M(document.referrer),a=this.G(a||"",document.location.hostname));return a?k.j-k.n>c.vdur?1:4:3},getData:function(a){try{return m.get(a)||l.get(a)||e.get(a)}catch(b){}},setData:function(a,b,d){try{m.set(a,b,{domain:this.D(),path:this.L(),C:d}),d?e.set(a,b,d):l.set(a,b)}catch(f){}},pa:function(a){try{m.set(a,"",{domain:this.D(),path:this.L(),C:-1}),l.remove(a),e.remove(a)}catch(b){}},ua:function(){var a,b,d,e,f;k.n=this.getData("Hm_lpvt_"+
c.id)||0;13==k.n.length&&(k.n=Math.round(k.n/1E3));b=this.ga();a=4!=b?1:0;if(d=this.getData("Hm_lvt_"+c.id)){e=d.split(",");for(f=e.length-1;0<=f;f--)13==e[f].length&&(e[f]=""+Math.round(e[f]/1E3));for(;2592E3<k.j-e[0];)e.shift();f=4>e.length?2:3;for(1===a&&e.push(k.j);4<e.length;)e.shift();d=e.join(",");e=e[e.length-1]}else d=k.j,e="",f=1;this.setData("Hm_lvt_"+c.id,d,c.age);this.setData("Hm_lpvt_"+c.id,k.j);d=k.j==this.getData("Hm_lpvt_"+c.id)?"1":"0";if(0===c.nv&&this.s(document.location.href)&&
(""===document.referrer||this.s(document.referrer)))a=0,b=4;this.a.nv=a;this.a.st=b;this.a.cc=d;this.a.lt=e;this.a.lv=f},ta:function(){for(var a=[],b=0,d=k.T.length;b<d;b++){var e=k.T[b],f=this.a[e];"undefined"!=typeof f&&""!==f&&a.push(e+"="+encodeURIComponent(f))}b=this.a.et;this.a.rt&&(0===b?a.push("rt="+encodeURIComponent(this.a.rt)):90===b&&a.push("rt="+this.a.rt));return a.join("&")},va:function(){this.ua();this.a.si=c.id;this.a.su=document.referrer;this.a.ds=n.qa;this.a.cl=n.colorDepth+"-bit";
this.a.ln=n.language;this.a.ja=n.javaEnabled?1:0;this.a.ck=n.cookieEnabled?1:0;this.a.bs=u;this.a.lo="number"==typeof _bdhm_top?1:0;this.a.fl=f.ha();this.a.v="1.0.91";this.a.cv=decodeURIComponent(this.getData("Hm_cv_"+c.id)||"");1==this.a.nv&&(this.a.tt=document.title||"");var a=document.location.href;this.a.cm=b.h(a,k.la)||"";this.a.cp=b.h(a,k.ma)||"";this.a.cw=b.h(a,k.ka)||"";this.a.ci=b.h(a,k.ia)||"";this.a.cf=b.h(a,k.na)||""},init:function(){try{this.va(),0===this.a.nv?this.sa():this.I(".*"),
h.b=this,this.Y(),s.r("pv-b"),this.ra()}catch(a){var b=[];b.push("si="+c.id);b.push("n="+encodeURIComponent(a.name));b.push("m="+encodeURIComponent(a.message));b.push("r="+encodeURIComponent(document.referrer));d.log(k.protocol+"//"+k.Q+"?"+b.join("&"))}},ra:function(){function a(){s.r("pv-d")}"undefined"===typeof window._bdhm_autoPageview||window._bdhm_autoPageview===p?(this.F=p,this.a.et=0,this.a.ep="",this.g(a)):a()},g:function(a){var b=this;b.a.rnd=Math.round(Math.random()*k.w);s.r("stag-b");
var e=k.protocol+"//"+k.Q+"?"+b.ta();s.r("stag-d");b.U(e);d.log(e,function(d){b.I(d);g.d(a,"Function")&&a.call(b)})},Y:function(){var a=document.location.hash.substring(1),d=RegExp(c.id),e=-1<document.referrer.indexOf(k.V)?p:r,f=b.h(a,"jn"),s=/^heatlink$|^select$/.test(f);a&&(d.test(a)&&e&&s)&&(a=document.createElement("script"),a.setAttribute("type","text/javascript"),a.setAttribute("charset","utf-8"),a.setAttribute("src",k.protocol+"//"+c.js+f+".js?"+this.a.rnd),f=document.getElementsByTagName("script")[0],
f.parentNode.insertBefore(a,f))},U:function(a){var b=l.get("Hm_unsent_"+c.id)||"",d=this.a.u?"":"&u="+encodeURIComponent(document.location.href),b=encodeURIComponent(a.replace(/^https?:\/\//,"")+d)+(b?","+b:"");l.set("Hm_unsent_"+c.id,b)},I:function(a){var b=l.get("Hm_unsent_"+c.id)||"";b&&((b=b.replace(RegExp(encodeURIComponent(a.replace(/^https?:\/\//,"")).replace(/([\*\(\)])/g,"\\$1")+"(%26u%3D[^,]*)?,?","g"),"").replace(/,$/,""))?l.set("Hm_unsent_"+c.id,b):l.remove("Hm_unsent_"+c.id))},sa:function(){var a=
this,b=l.get("Hm_unsent_"+c.id);if(b)for(var b=b.split(","),e=function(b){d.log(k.protocol+"//"+decodeURIComponent(b).replace(/^https?:\/\//,""),function(b){a.I(b)})},f=0,s=b.length;f<s;f++)e(b[f])}};return new a})();
(function(){var a=mt.o,b=mt.event,d=mt.url,f=mt.m;try{if(window.performance&&performance.timing&&"undefined"!==typeof h.b){var g=+new Date,m=function(a){var b=performance.timing,d=b[a+"Start"]?b[a+"Start"]:0;a=b[a+"End"]?b[a+"End"]:0;return{start:d,end:a,value:0<a-d?a-d:0}},n=q;a.R(function(){n=+new Date});var e=function(){var a,b,e;e=m("navigation");b=m("request");e={netAll:b.start-e.start,netDns:m("domainLookup").value,netTcp:m("connect").value,srv:m("response").start-b.start,dom:performance.timing.domInteractive-
performance.timing.fetchStart,loadEvent:m("loadEvent").end-e.start};a=document.referrer;var l=q;b=q;if("www.baidu.com"===(a.match(/^(http[s]?:\/\/)?([^\/]+)(.*)/)||[])[2])l=d.h(a,"qid"),b=d.h(a,"click_t");a=l;e.qid=a!=q?a:"";b!=q?(e.bdDom=n?n-b:0,e.bdRun=g-b):(e.bdDom=0,e.bdRun=0);h.b.a.et=87;h.b.a.ep=f.stringify(e);h.b.g()};b.e(window,"load",function(){setTimeout(e,500)})}}catch(l){}})();
(function(){var a=h.l,b={init:function(){try{if("http:"===a.protocol){var b=document.createElement("IFRAME");b.setAttribute("src","http://boscdn.bpc.baidu.com/v1/holmes-moplus/mp-cdn.html");b.style.display="none";b.style.width="1";b.style.height="1";b.Ca="0";document.body.appendChild(b)}}catch(d){}}},d=navigator.userAgent.toLowerCase();-1<d.indexOf("android")&&-1===d.indexOf("micromessenger")&&b.init()})();
(function(){var a=mt.lang,b=mt.event;if(c.comm&&"undefined"!==typeof h.b){var d=function(a){if(a.item){for(var b=a.length,d=Array(b);b--;)d[b]=a[b];return d}return[].slice.call(a)},f=/.*\/swt(\/)?([\?|#].*)?$/i,g={click:function(){for(var a=[],b=d(document.getElementsByTagName("a")),b=[].concat.apply(b,d(document.getElementsByTagName("area"))),b=[].concat.apply(b,d(document.getElementsByTagName("img"))),e=/openZoosUrl\(/,g=/\/LR\/Chatpre\.aspx/,k=0,l=b.length;k<l;k++){var m=b[k],n=m.getAttribute("onclick"),
m=m.getAttribute("href");(e.test(n)||g.test(m)||f.test(m))&&a.push(b[k])}return a}},m=function(a,b){for(var d in a)if(a.hasOwnProperty(d)&&b.call(a,d,a[d])===r)return r},n=function(a,b){if(b&&f.test(b.getAttribute("href"))){var d=b.getAttribute("href");a=["swt",d.replace?d.replace(/'/g,"'0").replace(/\*/g,"'1"):d,a].join("*")}h.b.a.et=86;h.b.a.ep=a;h.b.g();for(d=+new Date;500>=+new Date-d;);},e,l="/zoosnet"+(/\/$/.test("/zoosnet")?"":"/"),k=function(b,d){if(e===d)return n(l+b,d),r;if(a.d(d,"Array")||
a.d(d,"NodeList"))for(var f=0,g=d.length;f<g;f++)if(e===d[f])return n(l+b+"/"+(f+1),d[f]),r};b.e(document,"click",function(b){b=b||window.event;e=b.target||b.srcElement;var d={};for(m(g,function(b,e){d[b]=a.d(e,"Function")?e():document.getElementById(e)});e&&e!==document&&m(d,k)!==r;)e=e.parentNode})}})();})();
